# Generated by Django 5.0.3 on 2024-05-28 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0002_chat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
