# Generated by Django 5.0.3 on 2024-04-03 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('phone', models.IntegerField()),
                ('is_recruiter', models.BooleanField(default=False)),
                ('is_applicant', models.BooleanField(default=True)),
                ('is_fresher', models.BooleanField(default=False)),
                ('experience', models.CharField(default=0, max_length=100)),
                ('profile_pic', models.ImageField(upload_to='image/profile')),
                ('resume', models.FileField(blank=True, null=True, upload_to='resume')),
                ('highest_qualification', models.CharField(choices=[('B.Tech', 'B.Tech'), ('B.E', 'B.E'), ('B.Sc', 'B.Sc'), ('B.Com', 'B.Com'), ('B.A', 'B.A'), ('M.Tech', 'M.Tech'), ('M.E', 'M.E'), ('M.Sc', 'M.Sc'), ('M.Com', 'M.Com'), ('M.A', 'M.A'), ('Phd', 'Phd'), ('Diploma', 'Diploma')], max_length=100)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='addLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Github', 'Github'), ('LinkedIn', 'LinkedIn'), ('Twitter', 'Twitter'), ('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('Geeks For Geeks', 'Geeks For Geeks'), ('Hackerrank', 'Hackerrank'), ('Hackerearth', 'Hackerearth'), ('Codechef', 'Codechef'), ('Codeforces', 'Codeforces'), ('Leetcode', 'Leetcode'), ('Dev.to', 'Dev.to'), ('Medium', 'Medium'), ('Stackoverflow', 'Stackoverflow'), ('Other', 'Other')], max_length=100)),
                ('link', models.CharField(help_text='Put yur  link here', max_length=100)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='job.applicantprofile')),
            ],
        ),
        migrations.CreateModel(
            name='achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateField()),
                ('Institution', models.CharField(max_length=40, null=True)),
                ('userprofile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='achievement', to='job.applicantprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(choices=[('B.Tech', 'B.Tech'), ('B.E', 'B.E'), ('B.Sc', 'B.Sc'), ('B.Com', 'B.Com'), ('B.A', 'B.A'), ('M.Tech', 'M.Tech'), ('M.E', 'M.E'), ('M.Sc', 'M.Sc'), ('M.Com', 'M.Com'), ('M.A', 'M.A'), ('Phd', 'Phd'), ('Diploma', 'Diploma'), ('HighSchool', 'HighSchool'), ('Intermediate', 'Intermediate')], max_length=100)),
                ('college', models.CharField(max_length=100)),
                ('board_or_university', models.CharField(max_length=100)),
                ('passing_year', models.CharField(max_length=100)),
                ('percentage', models.CharField(max_length=100)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='job.applicantprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('currently_working', models.BooleanField(default=False)),
                ('end_date', models.DateField()),
                ('userprofile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='job.applicantprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('is_recruiter', models.BooleanField(default=False)),
                ('is_applicant', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=100)),
                ('is_read', models.BooleanField(default=False)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='job.profile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='job.profile')),
            ],
            options={
                'ordering': ['is_read', '-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='job.profile'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(help_text='Describe your project')),
                ('start_date', models.DateField()),
                ('currently_working', models.BooleanField(default=False)),
                ('end_date', models.DateField()),
                ('Gitlink', models.CharField(max_length=100)),
                ('link', models.CharField(help_text='Put yur web  hosting link here', max_length=100)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='job.applicantprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_recruiter', models.BooleanField(default=True)),
                ('is_applicant', models.BooleanField(default=False)),
                ('company_name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='logo')),
                ('about_company', models.TextField()),
                ('company_address', models.CharField(max_length=100)),
                ('company_website', models.CharField(max_length=100)),
                ('company_email', models.CharField(max_length=100)),
                ('recruting_face', models.CharField(max_length=100)),
                ('grade', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter', to='job.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('Responsibilities', models.TextField(blank=True, null=True)),
                ('Qualifications', models.TextField(blank=True, null=True)),
                ('title', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('skills', models.CharField(max_length=22)),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('experience', models.CharField(max_length=100)),
                ('job_type', models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Internship', 'Internship'), ('other', 'other')], max_length=100)),
                ('vacancy', models.IntegerField(default=1)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='job.job_category')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.recruiter')),
            ],
        ),
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('about', models.TextField(help_text='Why should we hire you')),
                ('applied_on', models.DateTimeField(auto_now_add=True)),
                ('job_status', models.CharField(choices=[('Resume Sent', 'Resume Sent'), ('Resume Viewed', 'Resume viewed'), ('Not selected', 'Not selected'), ('In Process', 'In Process'), ('Hired', 'Hired'), ('Resume Shortlisted', 'Resume Shortlisted')], default='Resume Sent', max_length=100)),
                ('candidate_detail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='job.applicantprofile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.job')),
                ('recruiter_detail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='job.recruiter')),
            ],
        ),
        migrations.CreateModel(
            name='SaveJob',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('saved_on', models.DateTimeField(auto_now_add=True)),
                ('candidate_detail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='job.applicantprofile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.job')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='job.applicantprofile')),
            ],
        ),
    ]
