# Generated by Django 4.2.4 on 2023-09-19 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('phone', models.IntegerField()),
                ('is_recruiter', models.BooleanField(default=False)),
                ('is_applicant', models.BooleanField(default=True)),
                ('is_fresher', models.BooleanField(default=False)),
                ('current_ctc', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=100)),
                ('expected_ctc', models.CharField(max_length=100)),
                ('graduated_from', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('skills', models.CharField(max_length=100)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resume')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('is_recruiter', models.BooleanField(default=False)),
                ('is_applicant', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('basic', 'basic'), ('moderate', 'moderate'), ('advanced', 'advanced')], max_length=100)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='job.applicantprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_recruiter', models.BooleanField(default=True)),
                ('is_applicant', models.BooleanField(default=False)),
                ('company_name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='logo')),
                ('about_company', models.TextField()),
                ('company_address', models.CharField(max_length=100)),
                ('company_website', models.CharField(max_length=100)),
                ('company_email', models.CharField(max_length=100)),
                ('recruting_face', models.CharField(max_length=100)),
                ('grade', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='job.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(help_text='Describe your project')),
                ('start_date', models.DateField()),
                ('currently_working', models.BooleanField(default=False)),
                ('end_date', models.DateField()),
                ('Gitlink', models.CharField(max_length=100)),
                ('link', models.CharField(help_text='Put yur web  hosting link here', max_length=100)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='job.applicantprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('skills', models.CharField(max_length=22)),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('experience', models.CharField(max_length=100)),
                ('job_type', models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Internship', 'Internship'), ('other', 'other')], max_length=100)),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.recruiter')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=100)),
                ('board_or_university', models.CharField(max_length=100)),
                ('passing_year', models.CharField(max_length=100)),
                ('percentage', models.CharField(max_length=100)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='job.applicantprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('about', models.TextField(help_text='Why should we hire you')),
                ('applied_on', models.DateTimeField(auto_now_add=True)),
                ('candidate_detail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='job.applicantprofile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.job')),
                ('recruiter_detail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='job.recruiter')),
            ],
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='job.profile'),
        ),
    ]
