# Generated by Django 4.2.4 on 2023-09-24 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='applicantprofile',
            name='current_ctc',
        ),
        migrations.RemoveField(
            model_name='applicantprofile',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='applicantprofile',
            name='expected_ctc',
        ),
        migrations.RemoveField(
            model_name='applicantprofile',
            name='graduated_from',
        ),
        migrations.RemoveField(
            model_name='applicantprofile',
            name='skills',
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='highest_qualification',
            field=models.CharField(choices=[('B.Tech', 'B.Tech'), ('B.E', 'B.E'), ('B.Sc', 'B.Sc'), ('B.Com', 'B.Com'), ('B.A', 'B.A'), ('M.Tech', 'M.Tech'), ('M.E', 'M.E'), ('M.Sc', 'M.Sc'), ('M.Com', 'M.Com'), ('M.A', 'M.A'), ('Phd', 'Phd'), ('Diploma', 'Diploma')], default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='profile_pic',
            field=models.ImageField(default='', upload_to='image/profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='Qualifications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='Responsibilities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='experience',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='job.job_category'),
        ),
    ]
