# Generated by Django 4.2.4 on 2023-09-25 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_alter_education_degree'),
    ]

    operations = [
        migrations.CreateModel(
            name='addLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Github', 'Github'), ('LinkedIn', 'LinkedIn'), ('Twitter', 'Twitter'), ('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('Geeks For Geeks', 'Geeks For Geeks'), ('Hackerrank', 'Hackerrank'), ('Hackerearth', 'Hackerearth'), ('Codechef', 'Codechef'), ('Codeforces', 'Codeforces'), ('Leetcode', 'Leetcode'), ('Dev.to', 'Dev.to'), ('Medium', 'Medium'), ('Stackoverflow', 'Stackoverflow'), ('Other', 'Other')], max_length=100)),
                ('link', models.CharField(help_text='Put yur web  hosting link here', max_length=100)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='job.applicantprofile')),
            ],
        ),
    ]
