# Generated by Django 4.2.4 on 2023-09-25 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_addlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addlink',
            name='link',
            field=models.CharField(help_text='Put yur  link here', max_length=100),
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('currently_working', models.BooleanField(default=False)),
                ('end_date', models.DateField()),
                ('userprofile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='job.applicantprofile')),
            ],
        ),
    ]
